package com.example.demoSpringInitializrForEvoBJ.websocket.message;

public enum EMessageType {
    AUTHORIZATION,
    AUTHORIZATION_ERROR,
    MAIN_FORM_INITIALIZATION,

    CURRENT_DATA_ABOUT_PLAYER,

    CLIENT_COUNT,
    TABLE_STATUS,


    SEATS,
    TAKE_SEAT,
    UPDATE_SEAT_BET,
    LEAVE_SEAT,

    REQUEST_TO_START_GAME,
    GAME_STARTED,
    GAME_DECISION,
    E_GAME_RESULT_STATUS,
    DEALER,
    CURRENT_SEAT,
    CHANGED_SEAT_FOR_GAME,
    E_GAME_STATUS_FOR_INTERFACE,
    GAME_RESULTS,
    GAME_FINISHED,
    FRESH_DTOS,

    TIMER,
    TIMER_CANCEL,



    SYSTEM_ERROR,//TODO
    VALIDATION_ERROR,//TODO
    SOME_VALIDATION_ERROR,

    CLIENT_COUNT_ERROR,
    TAKE_SEAT_OK,
    UPDATE_SEAT_BET_OK,
    LEAVE_SEAT_OK,
    LEAVE_SEAT_ERROR,
    SEAT_ERROR,
}